name       : kinit
version    : 5.58.0
release    : 28
source     :
    - https://download.kde.org/stable/frameworks/5.58/kinit-5.58.0.tar.xz : 22c2adb9b1b52d0f90db9c36bd0313250d986a207f781c0582e85c4805297e53
license    : LGPL-2.1-or-later
component  : desktop.library
autodep    : no
optimize   : lto
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
