name       : kinit
version    : 5.66.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kinit-5.66.0.tar.xz : 6d9b6ea1542ff5529fd42f49240be37bbd8a3dfdfe8c45ac980b3c9b3fee650e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
autodep    : no
optimize   : lto
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
