name       : kinit
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kinit-5.25.0.tar.xz : dda2b28923d06521d4f501f76e3b20e44ef9ace59b9285635d7d173ef975bcfd
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - ki18n-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBEXECDIR=%libdir% .
build      : |
    %make
install    : |
    %make_install
