name       : kinit
version    : 5.51.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kinit-5.51.0.tar.xz : 1464902a9266c302ed48f7b9ebfd5a11944c4eddb4da805b4ec560163bf644b7
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
autodep    : no
optimize   : lto
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
