name       : kinit
version    : 5.80.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kinit-5.80.0.tar.xz : df256d1cb082de845a6f8d18b372694130c83e9b800033f0987d1929fcdc3480
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
autodep    : no
optimize   : lto
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(x11)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
rundeps    :
    - kservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
