name       : kinit
version    : 5.43.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kinit-5.43.0.tar.xz : eda5f372db7b08484c7109aa9077c7a2d36ddb17ed6b4e82703b13b427c93fcb
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
autodep    : no
optimize   : lto
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
