name       : kinit
version    : 5.39.0
release    : 9
source     :
    - https://download.kde.org/stable/frameworks/5.39/kinit-5.39.0.tar.xz : c26a88e6c3e0607bdfa1b51ae6fa0d7fa6bb863c9f8f2659e8622d0d77a05c28
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
autodep    : no
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
