name       : kinit
version    : 5.40.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kinit-5.40.0.tar.xz : ca97eb8480a7387537166831a6a91892068656a161b9726429af581a436e2689
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
autodep    : no
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
