name       : kinit
version    : 5.71.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kinit-5.71.0.tar.xz : 6ea625bced2c19b0f3e5bb504775dd6764358f02412364a16cbad731c5c299b6
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
autodep    : no
optimize   : lto
summary    : Helper library to speed up start of applications on KDE workspaces.
description: |
    Helper library to speed up start of applications on KDE workspaces.
patterns   :
    - /usr/lib64/libkdeinit5_klauncher.so
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kwindowsystem-devel
rundeps    :
    - kservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
